### ISSUE TITLE
Implement logic of Edit Entry

### ISSUE THREAD

**Issue by Wissben** [mohammedi-haroune/arabic-historical-dictionary-frontend#14]
In the dictionary2 view, the edit entry operation is still un-implemented, we should do it as quickly as possible :nerd_face:

**Comment by mohammedi-haroune** [comment]
Sure! 

@Wissben please consider being more specific when submitting issues 

> **we** should do it as quickly as possible nerd_face

should be: 

> **you** should do it as quickly as possible nerd_face
