### ISSUE TITLE
adding entry doesn't update

### ISSUE THREAD

**Issue by ressay** [mohammedi-haroune/arabic-historical-dictionary-frontend#2]
Like reading documents, adding an entry from the document keeps the information added on the previous entry.

**Comment by mohammedi-haroune** [comment]
I've removed `keep-alive` tag from `router-view` in the `App.view`

This should be fixed now!

**Comment by mohammedi-haroune** [comment]
related to #1

**Comment by ressay** [comment]
still not working in same document

**Comment by ressay** [comment]
it's working thanks
