### ISSUE TITLE
useless buttons?

### ISSUE THREAD

**Issue by ressay** [mohammedi-haroune/arabic-historical-dictionary-frontend#4]
![screenshot from 2018-12-14 19-12-48](https://user-images.githubusercontent.com/9249716/50019815-4de80100-ffd4-11e8-83e6-4ba60816c03d.png)
are these buttons supposed to work? in add entry => new historical example/new meaning

**Comment by mohammedi-haroune** [comment]
yeah, these buttons allow you to add as many meanings or historical examples as you want.

Want you say that we shouldn't be able to add more than one historical example from the selection in the corpus browser view?

**Comment by ressay** [comment]
No I just meant that they are not working right now, are you aware of that?

**Comment by mohammedi-haroune** [comment]
Below are some screen shots after clicking the buttons many times
Don't you have the same behaviour ?
![meanins](https://user-images.githubusercontent.com/23096288/50040798-95a96f80-004a-11e9-8ccc-eed5815de1f7.png)
![examples](https://user-images.githubusercontent.com/23096288/50040800-9a6e2380-004a-11e9-9750-beb9550d7991.png)

**Comment by ressay** [comment]
it is working now, not sure why it didn't last time I tried

**Comment by mohammedi-haroune** [comment]
the button click event doesn't trigger when you click and move the mouse simultaneously, I think this was the problem for you !
